target-version = "py312"
line-length = 100

exclude = [
    ".venv",
    "__pycache__",
    "data",
    "docs",
    "node_modules"
]

[lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]  # Игнорировать превышение длины строки для длинных описаний